export function addForecastQuestionOpenapi(document:any) {
  const context={oneOf:[
    {type:"object",additionalProperties:false,required:["kind","id"],properties:{kind:{type:"string",enum:["ensemble","game","saved_game","sagemaker"]},id:{type:"string",pattern:"^[A-Za-z0-9_-]{1,220}$"}}},
    {type:"object",additionalProperties:false,required:["kind","symbol","scan_id"],properties:{kind:{const:"screener"},symbol:{type:"string",maxLength:40},scan_id:{type:"string",maxLength:160}}},
    {type:"object",additionalProperties:false,required:["kind","name","frequency","rows"],properties:{kind:{const:"preview"},name:{type:"string",minLength:1,maxLength:120},frequency:{type:"string",maxLength:40},rows:{type:"array",minItems:2,maxItems:500,items:{type:"object",required:["timestamp","target"],properties:{timestamp:{type:"string",format:"date-time"},target:{type:"number"}}}}}},
  ],description:"References are resolved and authorized server-side. Client-supplied forecast arrays are rejected. Preview rows are explicitly user-supplied observations, not verified provider data."};
  document.components.schemas.JevForecastContext=context;
  const answer={type:"object",properties:{schema_version:{const:"forecast_question_v1"},model:{const:"jev-1.13.0"},response_mode:{const:"typed_routing_computed_facts"},heading:{type:"string"},answer:{type:"string"},topic:{type:"string"},facts:{type:"array",items:{type:"object",properties:{label:{type:"string"},value:{type:["string","number"]},kind:{enum:["observed","forecast","metadata"]},timestamp:{type:"string",format:"date-time"}}}},context_hash:{type:"string"},references:{type:"array",items:{type:"object"}},suggestions:{type:"array",items:{type:"object"}}}};
  document.components.schemas.JevForecastAnswer=answer;
  const errors={"401":{description:"Sign-in required or invalid authentication."},"403":{description:"Paid API entitlement, scope or current resource access denied."},"404":{description:"Saved or published context unavailable."},"409":{description:"Context changed, conversation busy, or 30-turn limit reached."},"422":{description:"Invalid reference, question, turn ID or annotation."},"429":{description:"Per-user or global Scout budget reached."},"503":{description:"Scout unavailable; no substitute answer is generated."}};
  document.tags.push({name:"Scout forecast questions",description:"Typed question routing with numerical answers calculated from authorized saved data. Conversations and notes are private to their owner. SageMaker references resolve repository CSVs, including exports with predictions but no input history. Supplied model metrics retain their evaluation basis."});
  const response=(description:string,example:any)=>({description,content:{"application/json":{schema:{type:"object"},example}}});
  document.paths["/jev/forecast-questions"]={post:{tags:["Scout forecast questions"],operationId:"askJevForecastQuestion",summary:"Ask Scout About An Authorized Forecast And Save Its Answer", "x-quantura-scope":"forecasts:read",
    description:"Scout classifies topic, quantile and statistic. Quantura computes facts from immutable input/forecast values, up to 500 history rows and 512 forecast steps. It does not generate trading returns or infer win rates. Reuse conversation_id and turn_id on retries; a completed turn returns its saved response without another model call. Each conversation has up to 30 turns. Web sessions require sign-in; programmatic calls require active metered or legacy Pro access (including an active 14-day trial), enterprise access or the verified admin. Owner/resource access is rechecked on every call.",
    requestBody:{required:true,content:{"application/json":{schema:{type:"object",additionalProperties:false,required:["context","question","turn_id"],properties:{context:{$ref:"#/components/schemas/JevForecastContext"},question:{type:"string",minLength:1,maxLength:1500},conversation_id:{type:"string",format:"uuid"},turn_id:{type:"string",format:"uuid"}}},example:{context:{kind:"ensemble",id:"ens_saved_forecast"},question:"What is the maximum P50 across this forecast?",conversation_id:"5c71cfa6-57f8-4a69-941d-73cadfd6d263",turn_id:"e5eb1e65-881d-412a-a31b-5cf1b72a3eaf"}}}},
    responses:{"200":response("Saved structured answer with computed facts and source metadata.",{data:{conversation_id:"5c71cfa6-57f8-4a69-941d-73cadfd6d263",question:"What is the maximum P50 across this forecast?",response:{schema_version:"forecast_question_v1",model:"jev-1.13.0",response_mode:"typed_routing_computed_facts",heading:"Forecast values",topic:"values",answer:"Values come from the saved forecast.",facts:[{label:"max P50",value:346.81,kind:"forecast",timestamp:"2026-10-06T00:00:00Z"}]}}}),...errors}}};
  document.paths["/jev/conversations/{id}"]={get:{tags:["Scout forecast questions"],operationId:"getJevConversation",summary:"Reopen Your Saved Scout Conversation After Checking Current Forecast Access", "x-quantura-scope":"forecasts:read",parameters:[{name:"id",in:"path",required:true,schema:{type:"string",format:"uuid"}}],responses:{"200":response("Owner-only saved conversation.",{data:{conversation_id:"5c71cfa6-57f8-4a69-941d-73cadfd6d263",title:"SPY",context_reference:{kind:"ensemble",id:"ens_saved_forecast"},messages:[]}}),...errors}}};
  for(const action of ["read","save"])document.paths[`/jev/annotations/${action}`]={post:{tags:["Scout forecast questions"],operationId:action==="read"?"readForecastAnnotations":"saveForecastAnnotations",summary:action==="read"?"Read Your Private Chart Notes For This Authorized Forecast Context":"Save Private Chart Notes Anchored To Real Observed Or Forecast Points", "x-quantura-scope":"forecasts:read",
    requestBody:{required:true,content:{"application/json":{schema:{type:"object",additionalProperties:false,required:action==="save"?["context","notes"]:["context"],properties:{context:{$ref:"#/components/schemas/JevForecastContext"},notes:{type:"array",maxItems:20,items:{type:"object",additionalProperties:false,required:["id","text","timestamp","series"],properties:{id:{type:"string",format:"uuid"},text:{type:"string",minLength:1,maxLength:240},timestamp:{type:"string",format:"date-time"},series:{type:"string",description:"history or an exact available decimal quantile key."}}}}}}}}},
    responses:{"200":response("Private notes, with values derived server-side from existing points.",{data:{context_hash:"example-context-hash",notes:[]}}),...errors}}};
}
