import {FORECAST_FREQUENCY_INPUTS} from "./forecastFrequency";
/** Public discovery/download contracts; examples are illustrative, not live data. */
export function addQSearchOpenapi(document:any,origin:string):void {
  const response=(example:unknown)=>({description:"Successful response (illustrative example)",content:{"application/json":{schema:{type:"object"},example}}});
  const error={description:"Invalid request or provider unavailable",content:{"application/json":{schema:{type:"object"},example:{ok:false,error:"event_query_invalid",message:"Choose a provider event and a valid continuation cursor."}}}};
  const parameter=(name:string,type="string",extra:any={})=>({name,in:"query",required:false,schema:{type,...extra}});
  const mcp=(name:string)=>({"x-mint":{mcp:{enabled:true,name}}});
  const row={resource_type:"instrument",resource_id:"alpaca:AAPL",symbol:"AAPL",name:"Apple Inc.",asset_class:"equity",source:"alpaca",exchange:"NASDAQ",history_available:true,forecast_available:true};
  const contract={source:"kalshi",eventId:"EXAMPLE-GAME",marketId:"EXAMPLE-GAME-HOME",contractId:"EXAMPLE-GAME-HOME:YES",providerSymbol:"EXAMPLE-GAME-HOME",side:"yes",outcome:"Home",eventTitle:"Home vs Away",marketTitle:"Home to win"};
  const eventRow={resource_type:"prediction_market_contract",resource_id:"kalshi:"+contract.contractId,symbol:contract.providerSymbol,name:"Home · Home vs Away",asset_class:"prediction_market",source:"kalshi",exchange:"Kalshi",unit:"decimal probability (0–1)",history_available:true,forecast_available:true,event_id:contract.eventId,market_id:contract.marketId,contract_id:contract.contractId,side:contract.side,outcome:contract.outcome,contract};
  const add=(path:string,method:string,operation:any)=>{document.paths[path]={...document.paths[path],servers:[{url:origin+"/api"}],[method]:{tags:[method==="get"?"Search":"Download"],security:[],...operation}};};
  add("/market-search","get",{operationId:"searchQuanturaMarkets",summary:"Search stocks, Dukascopy instruments, perpetuals and event contracts",...mcp("quantura_search_markets"),
    description:"Bounded provider discovery, not an exhaustive index. Inspect errors and coverage. Optional ranking orders verified candidates; it cannot invent or select a contract.",
    parameters:[{...parameter("q"),required:true},parameter("source","string",{enum:["auto","alpaca","dukascopy","kalshi","polymarket_us","kalshi_perps"],default:"auto"}),parameter("mode","string",{enum:["open","live","any"],default:"open"}),parameter("limit","integer",{minimum:1,maximum:20,default:8}),parameter("rank","string",{enum:["true","false"],default:"false"})],
    responses:{"200":response({ok:true,query:"AAPL",count:1,groups:{alpaca:[row]},errors:{},coverage:"Bounded provider discovery."}),"400":error,"422":error,"429":error}});
  add("/market-data/dukascopy/instruments","get",{operationId:"listDukascopyInstruments",summary:"Browse every instrument in the complete Dukascopy catalog",parameters:[parameter("search"),parameter("offset","integer",{minimum:0}),parameter("limit","integer",{minimum:1,maximum:200,default:100})],responses:{"200":response({ok:true,provider:"dukascopy",instruments:[],total:1504,next_offset:100,stale:false}),"422":error}});
  add("/market-search/resolve","get",{operationId:"resolveQuanturaMarketLink",summary:"Resolve a Polymarket US or Kalshi market link",...mcp("quantura_resolve_market_link"),parameters:[{...parameter("url"),required:true}],
    description:"Only approved provider links. Choose the returned outcome/side explicitly. Use event browsing to discover related props and other contracts.",responses:{"200":response({ok:true,count:1,groups:{kalshi:[eventRow]},errors:{},coverage:"Provider-verified contracts for this link."}),"422":error,"404":error,"502":error}});
  add("/market-search/event","get",{operationId:"browseQuanturaEventMarkets",summary:"Browse an event's moneylines, props and related markets",...mcp("quantura_browse_event_markets"),
    parameters:[{...parameter("source","string",{enum:["kalshi","polymarket_us"]}),required:true},{...parameter("event_id"),required:true},parameter("cursor")],
    description:"Use the returned Polymarket event_slug or Kalshi event_id. Follow next_cursor unchanged for this same event. Kalshi related_events use official game links; follow each branch independently. No inferred cross-venue joins.",
    responses:{"200":response({ok:true,source:"kalshi",event_id:"EXAMPLE-GAME",title:"Example game",count:0,groups:{kalshi:[]},related_events:[{event_id:"EXAMPLE-TOTAL",label:"EXAMPLE-TOTAL",group:"Totals"}],related_complete:true,next_cursor:null,total_contracts:null,coverage:"Paged live and archived contracts for this event."}),"422":error,"404":error,"502":error,"429":error}});
  add("/market-search/capabilities","get",{operationId:"getQuanturaSearchCapabilities",summary:"List provider capabilities before selecting markets or intervals",...mcp("quantura_get_search_capabilities"),responses:{"200":response({ok:true,providers:{kalshi:{label:"Kalshi",assetClasses:["prediction_market"],search:true,history:true,forecasting:["prediction_market"],redistributionStatus:"review_required"}}}),"429":error}});
  add("/sports/prediction-markets/export","post",{operationId:"downloadQuanturaEventHistory",summary:"Download verified history for selected event outcomes and sides",
    description:"Pass full contract objects returned by Search. IDs and sides are reverified. Up to 25 contracts from one provider; maximum 90-day range. JSON attachments contain metadata and rows. Missing intervals remain explicit.",
    requestBody:{required:true,content:{"application/json":{schema:{type:"object",required:["source","contracts","start","end"],properties:{
      source:{type:"string",enum:["kalshi","polymarket_us"]},contracts:{type:"array",minItems:1,maxItems:25,items:{type:"object",required:["source","eventId","marketId","contractId","providerSymbol","side"],properties:{source:{type:"string"},eventId:{type:"string"},marketId:{type:"string"},contractId:{type:"string"},providerSymbol:{type:"string"},side:{type:"string",enum:["yes","no","long","short"]}}}},
      start:{type:"string",format:"date-time"},end:{type:"string",format:"date-time"},frequency:{type:"string",enum:["raw","1m","5m","15m","30m","1h","4h","1d","1w","1month","final"]},
      history_phase:{type:"string",enum:["auto","both","pregame","in_game"]},mode:{type:"string",enum:["normalized","raw","canvas"]},target:{type:"string",enum:["price","bid","ask","midpoint"]},missing:{type:"string",enum:["leave","drop","forward_fill"]},format:{type:"string",enum:["json","csv"],default:"csv"}
    }}}}},responses:{"200":response({metadata:{source:"kalshi",mode:"normalized",frequency:"1m",target:"price",history_phase:"both",history_phase_policy:"auto",history_phase_by_contract:{"EXAMPLE-YES":"both"}},rows:[{timestamp:"2026-09-18T18:01:00Z",contract_id:"EXAMPLE-YES",price:.52,source:"kalshi"}]}),"400":error,"404":error,"413":error,"422":error,"429":error,"502":error}});
  for(const option of [false,true]){
    const name=option?"options":"stocks";
    add(`/market-data/${name}/history`,"post",{operationId:option?"downloadQuanturaOptionHistory":"downloadQuanturaStockHistory",summary:option?"Download closing history for one verified option contract":"Download split-adjusted stock history with automatic provider routing",
      description:"Download previews JSON and exports that exact snapshot as CSV/JSON. Provider coverage varies; missing bars are not fabricated. format=csv returns a CSV attachment. No uploaded workspace files are exposed here.",
      requestBody:{required:true,content:{"application/json":{schema:{type:"object",required:[option?"contractSymbol":"symbol"],properties:{symbol:{type:"string"},contractSymbol:{type:"string"},source:{type:"string",enum:option?["auto","alpaca"]:["auto","alpaca","dukascopy"],default:"auto"},price_side:{type:"string",enum:["bid","ask"],default:"bid"},page_mode:{type:"boolean",description:"Dukascopy: retrieve bounded candle file pages; follow next_cursor using the same settings."},cursor:{type:"string"},start:{type:"string",format:"date-time"},end:{type:"string",format:"date-time"},timeframe:{type:"string",enum:option?["1Min","1Hour","1Day"]:FORECAST_FREQUENCY_INPUTS},limit:{type:"integer",enum:[500,1000,1500,2000,50000]},adjustment:{type:"string",enum:["raw","split","all"]},session:{type:"string",enum:["regular","extended"]},format:{type:"string",enum:["json","csv"]}}},example:{[option?"contractSymbol":"symbol"]:option?"AAPL261218C00250000":"AAPL",source:"auto",timeframe:"1Day",limit:500,adjustment:"split",format:"json"}}}},
      responses:{"200":{...response({ok:true,provider:"alpaca",sourceRequested:"auto",fallbackUsed:false,[option?"contractSymbol":"symbol"]:option?"AAPL261218C00250000":"AAPL",timeframe:"1Day",count:1,rows:[{timestamp:"2026-09-18T04:00:00Z",open:100,high:102,low:99,close:101,volume:1000}]}),description:"JSON rows or CSV attachment"},"400":error,"422":error,"429":error,"503":error}});
  }
  const instrumentSchema=structuredClone(document.paths["/market-data/stocks/history"].post.requestBody.content["application/json"].schema);
  instrumentSchema.properties.source.enum=["auto","alpaca","dukascopy","kalshi_perps"];
  instrumentSchema.properties.frequency={type:"string",enum:FORECAST_FREQUENCY_INPUTS,description:"Alias for timeframe. Perpetuals support the same completed-bar frequencies."};
  instrumentSchema.properties.limit={type:"integer",minimum:1,maximum:50000,description:"Kalshi perpetuals: 1–5000; stocks/Dukascopy: 500, 1000, 1500, 2000, 50000 (default 2000)."};
  const eventSchema=structuredClone(document.paths["/sports/prediction-markets/export"].post.requestBody.content["application/json"].schema);
  add("/market-data/history","post",{
    operationId:"downloadQuanturaMarketHistory",summary:"Download observed market history as CSV or JSON",
    description:"One endpoint for stocks (auto/alpaca), Dukascopy instruments, Kalshi perpetuals (kalshi_perps), and Kalshi/Polymarket US event contracts. Use source and symbol for instruments; use source, contracts, start and end for events. Perpetual prices are normalized to USD per underlying unit using provider contract scaling. No missing bars are filled. Perpetuals allow at most 5000 rows and 20000 intervals per date range. Follow Dukascopy next_cursor with page_mode=true and identical settings. CSV export requires a completed unpaged range. Provider licensing and available history still apply.",
    requestBody:{required:true,content:{"application/json":{schema:{oneOf:[instrumentSchema,eventSchema]},examples:{stock:{value:{source:"alpaca",symbol:"AAPL",timeframe:"1Day",limit:500,format:"json"}},perpetual:{value:{source:"kalshi_perps",symbol:"KXBTCPERP",frequency:"1h",limit:500,format:"json"}},dukascopy:{value:{source:"dukascopy",symbol:"XAUUSD",timeframe:"1h",limit:500,price_side:"bid",format:"json"}}}}}},
    responses:{"200":{...response({ok:true,provider:"kalshi_perps",symbol:"KXBTCPERP",frequency:"1h",count:1,rows:[{timestamp:"2026-09-20T12:00:00Z",close:81500}],metadata:{units:"USD per underlying unit",missing_intervals:"not_filled"}}),content:{...response({ok:true,count:0,rows:[]}).content,"text/csv":{schema:{type:"string"},example:"timestamp,close\r\n2026-09-20T12:00:00Z,81500"}}},"404":error,"422":error,"429":error,"502":error,"503":error}
  });

}
