FROM mcr.microsoft.com/vscode/devcontainers/python:0-3.11

# Note: git-lfs installation removed due to repository signature issues
# You can manually install git-lfs if needed using: apt-get install git-lfs

USER vscode
